# Generated by Django 6.0.1 on 2026-01-24 21:01

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Parceiro',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('empresa', models.CharField(max_length=100)),
                ('contato_nome', models.CharField(max_length=100)),
                ('email', models.EmailField(blank=True, max_length=254, null=True)),
                ('telefone', models.CharField(blank=True, max_length=20, null=True)),
                ('cidade', models.CharField(max_length=100)),
                ('status', models.CharField(choices=[('Bronze', 'Bronze'), ('Prata', 'Prata'), ('Ouro', 'Ouro'), ('Diamante', 'Diamante')], default='Bronze', max_length=20)),
                ('score_atual', models.DecimalField(decimal_places=1, default=0.0, max_digits=5)),
                ('ultima_indicacao', models.DateField(default=django.utils.timezone.now)),
                ('servicos', models.TextField(blank=True, help_text='Separe os serviços por vírgula')),
            ],
        ),
    ]
