# Generated by Django 6.0.1 on 2026-02-05 16:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='parceiro',
            name='score_atual',
            field=models.DecimalField(decimal_places=1, default=0.0, max_digits=10),
        ),
    ]
