# Generated by Django 6.0.1 on 2026-02-05 16:31

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_alter_parceiro_score_atual'),
    ]

    operations = [
        migrations.AddField(
            model_name='parceiro',
            name='estados_atuacao',
            field=models.CharField(blank=True, default='', help_text='Siglas dos estados separadas por vírgula (Ex: SP, RJ)', max_length=200),
        ),
        migrations.CreateModel(
            name='HistoricoPontuacao',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data', models.DateTimeField(auto_now_add=True)),
                ('tipo', models.CharField(max_length=50)),
                ('pontos', models.DecimalField(decimal_places=2, max_digits=5)),
                ('descricao', models.CharField(blank=True, max_length=255, null=True)),
                ('parceiro', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='historico', to='core.parceiro')),
            ],
            options={
                'ordering': ['-data'],
            },
        ),
    ]
