# Generated by Django 6.0.1 on 2026-02-06 05:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_parceiro_estados_atuacao_historicopontuacao'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='historicopontuacao',
            options={},
        ),
        migrations.RemoveField(
            model_name='parceiro',
            name='status',
        ),
        migrations.AlterField(
            model_name='historicopontuacao',
            name='data',
            field=models.DateField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='parceiro',
            name='cidade',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='parceiro',
            name='contato_nome',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='parceiro',
            name='email',
            field=models.EmailField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='parceiro',
            name='empresa',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='parceiro',
            name='estados_atuacao',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='parceiro',
            name='score_atual',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=10),
        ),
        migrations.AlterField(
            model_name='parceiro',
            name='servicos',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='parceiro',
            name='telefone',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='parceiro',
            name='ultima_indicacao',
            field=models.DateField(blank=True, null=True),
        ),
    ]
